title: "Sebastian Ritter"
description: "PhD Candidate in Economics"
theme: minima
plugins:
  - jekyll-feed

# Menú principal
nav:
  - name: Home
    link: /
  - name: Research
    link: /research/
  - name: Blog
    link: /blog/
  - name: Conferences and Seminars
    link: /conferences/
  - name: CV
    link: /cv/
