title: "Sebastian Ritter"
description: "PhD Candidate in Economics"
url: "https://sebastianritterg.github.io/"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag  

markdown: kramdown
kramdown:
  math_engine: mathjax

header_pages:
  - index.md
  - research.md
  - blog/index.md
  - conferences.md
  - cv.md
