title: "Sebastian Ritter"
description: "PhD Candidate in Economics"
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  math_engine: mathjax
header_pages:
  - index.md
  - research.md
  - blog/index.md
  - conferences.md
  - cv.md
