title: "Sebastian Ritter"
description: "PhD Candidate in Economics at the University of Barcelona | 2026-27 Economics Job Market"
author: "Sebastian Ritter"
url: "https://sebastianritterg.github.io/"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag  
  - jekyll-sitemap

markdown: kramdown
kramdown:
  math_engine: mathjax

header_pages:
  - index.md
  - research.md
  - cv.md
  - conferences.md
  - blog/index.md
